{"response":
    {"status":"ok",
        "userTier":"developer",
        "total":168022,"startIndex":51,
        "pageSize":10,"currentPage":6,
        "pages":16803,
        "orderBy":"relevance",
        "results":[
            {
                "id":"commentisfree/2023/sep/28/who-won-the-republican-debate-our-panel-responds",
                "type":"article",
                "sectionId":"commentisfree",
                "sectionName":"Opinion",
                "webPublicationDate":"2023-09-28T04:20:16Z",
                "webTitle":"Who won the Republican debate? Our panel responds | Panelists",
                "webUrl":"https://www.theguardian.com/commentisfree/2023/sep/28/who-won-the-republican-debate-our-panel-responds",
                "apiUrl":"https://content.guardianapis.com/commentisfree/2023/sep/28/who-won-the-republican-debate-our-panel-responds",
                "isHosted":false,
                "pillarId":"pillar/opinion",
                "pillarName":"Opinion"
            },
                {
                    "id":"world/2023/oct/26/arab-nations-condemn-israels-gaza-assault-during-un-debate",
                    "type":"article",
                    "sectionId":"world",
                    "sectionName":"World news",
                    "webPublicationDate":"2023-10-26T19:54:57Z",
                    "webTitle":"Arab nations condemn Israel’s Gaza assault during UN debate",
                    "webUrl":"https://www.theguardian.com/world/2023/oct/26/arab-nations-condemn-israels-gaza-assault-during-un-debate",
                    "apiUrl":"https://content.guardianapis.com/world/2023/oct/26/arab-nations-condemn-israels-gaza-assault-during-un-debate",
                    "isHosted":false,
                    "pillarId":"pillar/news",
                    "pillarName":"News"
                },
                    {
                        "id":"us-news/article/2024/may/15/biden-trump-debate-date",
                        "type":"article",
                        "sectionId":"us-news",
                        "sectionName":"US news",
                        "webPublicationDate":"2024-05-15T17:37:23Z",
                        "webTitle":"Joe Biden and Donald Trump agree to two US presidential debates",
                        "webUrl":"https://www.theguardian.com/us-news/article/2024/may/15/biden-trump-debate-date",
                        "apiUrl":"https://content.guardianapis.com/us-news/article/2024/may/15/biden-trump-debate-date",
                        "isHosted":false,
                        "pillarId":"pillar/news",
                        "pillarName":"News"
                    },
                    {"id":"us-news/article/2024/may/16/first-thing-joe-biden-and-donald-trump-agree-to-two-debates",
                        "type":"article",
                        "sectionId":"us-news","sectionName":"US news","webPublicationDate":"2024-05-16T10:38:15Z","webTitle":"First Thing: Joe Biden and Donald Trump agree to two debates","webUrl":"https://www.theguardian.com/us-news/article/2024/may/16/first-thing-joe-biden-and-donald-trump-agree-to-two-debates","apiUrl":"https://content.guardianapis.com/us-news/article/2024/may/16/first-thing-joe-biden-and-donald-trump-agree-to-two-debates","isHosted":false,"pillarId":"pillar/news","pillarName":"News"},{"id":"culture/2023/nov/10/seth-meyers-on-the-republican-primary-debate-a-demented-circus","type":"article","sectionId":"culture","sectionName":"Culture","webPublicationDate":"2023-11-10T15:34:44Z","webTitle":"Seth Meyers on the Republican primary debate: ‘A demented circus’","webUrl":"https://www.theguardian.com/culture/2023/nov/10/seth-meyers-on-the-republican-primary-debate-a-demented-circus","apiUrl":"https://content.guardianapis.com/culture/2023/nov/10/seth-meyers-on-the-republican-primary-debate-a-demented-circus","isHosted":false,"pillarId":"pillar/arts","pillarName":"Arts"},{"id":"us-news/2024/feb/06/biden-trump-presidential-debate","type":"article","sectionId":"us-news","sectionName":"US news","webPublicationDate":"2024-02-06T15:04:10Z","webTitle":"Biden dismisses Trump’s demand to ‘immediately’ schedule debate: ‘He’s got nothing else to do’","webUrl":"https://www.theguardian.com/us-news/2024/feb/06/biden-trump-presidential-debate","apiUrl":"https://content.guardianapis.com/us-news/2024/feb/06/biden-trump-presidential-debate","isHosted":false,"pillarId":"pillar/news","pillarName":"News"},{"id":"australia-news/2024/jan/17/lord-prayer-australian-parliament-mps-axed-calls-details","type":"article","sectionId":"australia-news","sectionName":"Australia news","webPublicationDate":"2024-01-16T14:00:03Z","webTitle":"Should Australian parliaments axe the Lord’s Prayer? In Victoria it’s up for debate","webUrl":"https://www.theguardian.com/australia-news/2024/jan/17/lord-prayer-australian-parliament-mps-axed-calls-details","apiUrl":"https://content.guardianapis.com/australia-news/2024/jan/17/lord-prayer-australian-parliament-mps-axed-calls-details","isHosted":false,"pillarId":"pillar/news","pillarName":"News"},{"id":"us-news/2023/dec/01/pugilistic-us-presidential-undercard-provides-snapshot-of-a-nation-divided-ron-desantis-gavin-newsome","type":"article","sectionId":"us-news","sectionName":"US news","webPublicationDate":"2023-12-01T10:14:49Z","webTitle":"Undercard for Biden-Trump? Debate puts two Americas on same stage","webUrl":"https://www.theguardian.com/us-news/2023/dec/01/pugilistic-us-presidential-undercard-provides-snapshot-of-a-nation-divided-ron-desantis-gavin-newsome","apiUrl":"https://content.guardianapis.com/us-news/2023/dec/01/pugilistic-us-presidential-undercard-provides-snapshot-of-a-nation-divided-ron-desantis-gavin-newsome","isHosted":false,"pillarId":"pillar/news","pillarName":"News"},{"id":"politics/article/2024/may/24/smaller-parties-may-be-squeezed-out-of-uk-election-tv-leadership-debates","type":"article","sectionId":"politics","sectionName":"Politics","webPublicationDate":"2024-05-24T12:00:55Z","webTitle":"Smaller parties may be squeezed out of UK election TV leadership debates","webUrl":"https://www.theguardian.com/politics/article/2024/may/24/smaller-parties-may-be-squeezed-out-of-uk-election-tv-leadership-debates","apiUrl":"https://content.guardianapis.com/politics/article/2024/may/24/smaller-parties-may-be-squeezed-out-of-uk-election-tv-leadership-debates","isHosted":false,"pillarId":"pillar/news","pillarName":"News"},{"id":"technology/2023/oct/24/hope-or-horror-the-great-ai-debate-dividing-its-pioneers","type":"article","sectionId":"technology","sectionName":"Technology","webPublicationDate":"2023-10-24T12:00:36Z","webTitle":"Hope or horror? The great AI debate dividing its pioneers","webUrl":"https://www.theguardian.com/technology/2023/oct/24/hope-or-horror-the-great-ai-debate-dividing-its-pioneers","apiUrl":"https://content.guardianapis.com/technology/2023/oct/24/hope-or-horror-the-great-ai-debate-dividing-its-pioneers","isHosted":false,"pillarId":"pillar/news","pillarName":"News"}]}}
